spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    io.github.qwertyhgb.knowflow: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
